# Generated by Django 3.1.4 on 2023-04-20 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokochaj_zwierzaka', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DISEASE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_urodzenia', models.DateField()),
                ('rasa', models.CharField(choices=[('ON', 'owczarek niemiecki'), ('LR', 'labrador retriever'), ('YR', 'yorkshire terrier'), ('SM', 'sznaucer miniaturowy'), ('BF', 'buldog francuski')], max_length=2)),
                ('imie', models.CharField(max_length=30)),
                ('charakter', models.TextField(max_length=1024)),
                ('specjalne_potrzeby', models.TextField(blank=True, default=None, max_length=1024, null=True)),
                ('choroby', models.TextField(blank=True, default=None, max_length=1024, null=True)),
                ('pobyt_w_schronisku', models.DateField()),
                ('fotografia', models.ImageField(blank=True, default=None, null=True, upload_to='static/images/dogsphotos/')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dopasowanie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wiek_psa', models.CharField(blank=True, choices=[('P1', 'do 1 roku'), ('P2', 'od 1 do 3 lat'), ('P3', 'od 3 do 5 lat'), ('P4', 'od 5 do 10 lat'), ('P5', 'ponad 10 lat')], max_length=2, null=True)),
                ('rasa_psa', models.CharField(blank=True, choices=[('ON', 'owczarek niemiecki'), ('LR', 'labrador retriever'), ('YR', 'yorkshire terrier'), ('SM', 'sznaucer miniaturowy'), ('BF', 'buldog francuski')], max_length=2, null=True)),
                ('czas_pobytu_w_schronisku', models.CharField(blank=True, choices=[('P1', 'do 1 roku'), ('P2', 'od 1 do 3 lat'), ('P3', 'od 3 do 5 lat'), ('P4', 'od 5 do 10 lat'), ('P5', 'ponad 10 lat')], max_length=2, null=True)),
                ('pies_ze_specjalnymi_wymaganiami', models.CharField(choices=[('T', 'tak'), ('N', 'nie')], default='T', max_length=1)),
                ('pies_z_chorobami', models.CharField(choices=[('T', 'tak'), ('N', 'nie')], default='T', max_length=1)),
                ('uzytkownik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UzytkownikPodstawa',
        ),
    ]
